/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIdRouteImport } from './routes/tutor.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedAiTutorRouteImport } from './routes/_authenticated/ai-tutor'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClassroomRoomIdRouteImport } from './routes/_authenticated/classroom.$roomId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIdRoute = TutorIdRouteImport.update({
  id: '/tutor/$id',
  path: '/tutor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiTutorRoute = AuthenticatedAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomRoomIdRoute =
  AuthenticatedClassroomRoomIdRouteImport.update({
    id: '/classroom/$roomId',
    path: '/classroom/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tutor/$id': typeof TutorIdRoute
  '/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tutor/$id': typeof TutorIdRoute
  '/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tutor/$id': typeof TutorIdRoute
  '/_authenticated/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/labs'
    | '/leaderboard'
    | '/reset-password'
    | '/admin'
    | '/ai-tools'
    | '/ai-tutor'
    | '/certificate'
    | '/code'
    | '/dashboard'
    | '/tutor/$id'
    | '/classroom/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/labs'
    | '/leaderboard'
    | '/reset-password'
    | '/admin'
    | '/ai-tools'
    | '/ai-tutor'
    | '/certificate'
    | '/code'
    | '/dashboard'
    | '/tutor/$id'
    | '/classroom/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community'
    | '/labs'
    | '/leaderboard'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/ai-tools'
    | '/_authenticated/ai-tutor'
    | '/_authenticated/certificate'
    | '/_authenticated/code'
    | '/_authenticated/dashboard'
    | '/tutor/$id'
    | '/_authenticated/classroom/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  LabsRoute: typeof LabsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TutorIdRoute: typeof TutorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$id': {
      id: '/tutor/$id'
      path: '/tutor/$id'
      fullPath: '/tutor/$id'
      preLoaderRoute: typeof TutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tutor': {
      id: '/_authenticated/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AuthenticatedAiTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classroom/$roomId': {
      id: '/_authenticated/classroom/$roomId'
      path: '/classroom/$roomId'
      fullPath: '/classroom/$roomId'
      preLoaderRoute: typeof AuthenticatedClassroomRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedAiTutorRoute: typeof AuthenticatedAiTutorRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClassroomRoomIdRoute: typeof AuthenticatedClassroomRoomIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedAiTutorRoute: AuthenticatedAiTutorRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClassroomRoomIdRoute: AuthenticatedClassroomRoomIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  LabsRoute: LabsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TutorIdRoute: TutorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
