/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIdRouteImport } from './routes/tutor.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLabsRouteImport } from './routes/_authenticated/labs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBecomeTutorRouteImport } from './routes/_authenticated/become-tutor'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAiTutorRouteImport } from './routes/_authenticated/ai-tutor'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedWhiteboardReviewSessionIdRouteImport } from './routes/_authenticated/whiteboard-review.$sessionId'
import { Route as AuthenticatedTutorHolidaysRouteImport } from './routes/_authenticated/tutor.holidays'
import { Route as AuthenticatedParentChildrenRouteImport } from './routes/_authenticated/parent.children'
import { Route as AuthenticatedClassroomRoomIdRouteImport } from './routes/_authenticated/classroom.$roomId'
import { Route as AuthenticatedBookTutorIdRouteImport } from './routes/_authenticated/book.$tutorId'
import { Route as AuthenticatedAdminWhiteboardRouteImport } from './routes/_authenticated/admin.whiteboard'
import { Route as AuthenticatedAdminTutorsRouteImport } from './routes/_authenticated/admin.tutors'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin.promotions'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as AuthenticatedAdminClassroomsRouteImport } from './routes/_authenticated/admin.classrooms'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIdRoute = TutorIdRouteImport.update({
  id: '/tutor/$id',
  path: '/tutor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabsRoute = AuthenticatedLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeTutorRoute =
  AuthenticatedBecomeTutorRouteImport.update({
    id: '/become-tutor',
    path: '/become-tutor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiTutorRoute = AuthenticatedAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhiteboardReviewSessionIdRoute =
  AuthenticatedWhiteboardReviewSessionIdRouteImport.update({
    id: '/whiteboard-review/$sessionId',
    path: '/whiteboard-review/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTutorHolidaysRoute =
  AuthenticatedTutorHolidaysRouteImport.update({
    id: '/tutor/holidays',
    path: '/tutor/holidays',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentChildrenRoute =
  AuthenticatedParentChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedClassroomRoomIdRoute =
  AuthenticatedClassroomRoomIdRouteImport.update({
    id: '/classroom/$roomId',
    path: '/classroom/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookTutorIdRoute =
  AuthenticatedBookTutorIdRouteImport.update({
    id: '/book/$tutorId',
    path: '/book/$tutorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWhiteboardRoute =
  AuthenticatedAdminWhiteboardRouteImport.update({
    id: '/admin/whiteboard',
    path: '/admin/whiteboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTutorsRoute =
  AuthenticatedAdminTutorsRouteImport.update({
    id: '/admin/tutors',
    path: '/admin/tutors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/admin/promotions',
    path: '/admin/promotions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/admin/commissions',
    path: '/admin/commissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClassroomsRoute =
  AuthenticatedAdminClassroomsRouteImport.update({
    id: '/admin/classrooms',
    path: '/admin/classrooms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tutors': typeof TutorsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/become-tutor': typeof AuthenticatedBecomeTutorRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/code': typeof AuthenticatedCodeRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/records': typeof AuthenticatedRecordsRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tutor/$id': typeof TutorIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classrooms': typeof AuthenticatedAdminClassroomsRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/whiteboard': typeof AuthenticatedAdminWhiteboardRoute
  '/book/$tutorId': typeof AuthenticatedBookTutorIdRoute
  '/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/tutor/holidays': typeof AuthenticatedTutorHolidaysRoute
  '/whiteboard-review/$sessionId': typeof AuthenticatedWhiteboardReviewSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tutors': typeof TutorsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/become-tutor': typeof AuthenticatedBecomeTutorRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/code': typeof AuthenticatedCodeRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/records': typeof AuthenticatedRecordsRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tutor/$id': typeof TutorIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classrooms': typeof AuthenticatedAdminClassroomsRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/whiteboard': typeof AuthenticatedAdminWhiteboardRoute
  '/book/$tutorId': typeof AuthenticatedBookTutorIdRoute
  '/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/tutor/holidays': typeof AuthenticatedTutorHolidaysRoute
  '/whiteboard-review/$sessionId': typeof AuthenticatedWhiteboardReviewSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tutors': typeof TutorsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/ai-tutor': typeof AuthenticatedAiTutorRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/become-tutor': typeof AuthenticatedBecomeTutorRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/labs': typeof AuthenticatedLabsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tutor/$id': typeof TutorIdRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/classrooms': typeof AuthenticatedAdminClassroomsRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/_authenticated/admin/whiteboard': typeof AuthenticatedAdminWhiteboardRoute
  '/_authenticated/book/$tutorId': typeof AuthenticatedBookTutorIdRoute
  '/_authenticated/classroom/$roomId': typeof AuthenticatedClassroomRoomIdRoute
  '/_authenticated/parent/children': typeof AuthenticatedParentChildrenRoute
  '/_authenticated/tutor/holidays': typeof AuthenticatedTutorHolidaysRoute
  '/_authenticated/whiteboard-review/$sessionId': typeof AuthenticatedWhiteboardReviewSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/help'
    | '/leaderboard'
    | '/reset-password'
    | '/tutors'
    | '/unsubscribe'
    | '/ai-tools'
    | '/ai-tutor'
    | '/assignments'
    | '/become-tutor'
    | '/calendar'
    | '/certificate'
    | '/code'
    | '/courses'
    | '/dashboard'
    | '/labs'
    | '/messages'
    | '/my-courses'
    | '/notes'
    | '/notifications'
    | '/parent'
    | '/records'
    | '/resources'
    | '/email/unsubscribe'
    | '/tutor/$id'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/classrooms'
    | '/admin/commissions'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/tutors'
    | '/admin/whiteboard'
    | '/book/$tutorId'
    | '/classroom/$roomId'
    | '/parent/children'
    | '/tutor/holidays'
    | '/whiteboard-review/$sessionId'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/help'
    | '/leaderboard'
    | '/reset-password'
    | '/tutors'
    | '/unsubscribe'
    | '/ai-tools'
    | '/ai-tutor'
    | '/assignments'
    | '/become-tutor'
    | '/calendar'
    | '/certificate'
    | '/code'
    | '/courses'
    | '/dashboard'
    | '/labs'
    | '/messages'
    | '/my-courses'
    | '/notes'
    | '/notifications'
    | '/parent'
    | '/records'
    | '/resources'
    | '/email/unsubscribe'
    | '/tutor/$id'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/classrooms'
    | '/admin/commissions'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/tutors'
    | '/admin/whiteboard'
    | '/book/$tutorId'
    | '/classroom/$roomId'
    | '/parent/children'
    | '/tutor/holidays'
    | '/whiteboard-review/$sessionId'
    | '/lovable/email/suppression'
    | '/admin'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community'
    | '/help'
    | '/leaderboard'
    | '/reset-password'
    | '/tutors'
    | '/unsubscribe'
    | '/_authenticated/ai-tools'
    | '/_authenticated/ai-tutor'
    | '/_authenticated/assignments'
    | '/_authenticated/become-tutor'
    | '/_authenticated/calendar'
    | '/_authenticated/certificate'
    | '/_authenticated/code'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/labs'
    | '/_authenticated/messages'
    | '/_authenticated/my-courses'
    | '/_authenticated/notes'
    | '/_authenticated/notifications'
    | '/_authenticated/parent'
    | '/_authenticated/records'
    | '/_authenticated/resources'
    | '/email/unsubscribe'
    | '/tutor/$id'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/classrooms'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/tutors'
    | '/_authenticated/admin/whiteboard'
    | '/_authenticated/book/$tutorId'
    | '/_authenticated/classroom/$roomId'
    | '/_authenticated/parent/children'
    | '/_authenticated/tutor/holidays'
    | '/_authenticated/whiteboard-review/$sessionId'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TutorsRoute: typeof TutorsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  TutorIdRoute: typeof TutorIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$id': {
      id: '/tutor/$id'
      path: '/tutor/$id'
      fullPath: '/tutor/$id'
      preLoaderRoute: typeof TutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labs': {
      id: '/_authenticated/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AuthenticatedLabsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-tutor': {
      id: '/_authenticated/become-tutor'
      path: '/become-tutor'
      fullPath: '/become-tutor'
      preLoaderRoute: typeof AuthenticatedBecomeTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tutor': {
      id: '/_authenticated/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AuthenticatedAiTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whiteboard-review/$sessionId': {
      id: '/_authenticated/whiteboard-review/$sessionId'
      path: '/whiteboard-review/$sessionId'
      fullPath: '/whiteboard-review/$sessionId'
      preLoaderRoute: typeof AuthenticatedWhiteboardReviewSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutor/holidays': {
      id: '/_authenticated/tutor/holidays'
      path: '/tutor/holidays'
      fullPath: '/tutor/holidays'
      preLoaderRoute: typeof AuthenticatedTutorHolidaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/children': {
      id: '/_authenticated/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AuthenticatedParentChildrenRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/classroom/$roomId': {
      id: '/_authenticated/classroom/$roomId'
      path: '/classroom/$roomId'
      fullPath: '/classroom/$roomId'
      preLoaderRoute: typeof AuthenticatedClassroomRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book/$tutorId': {
      id: '/_authenticated/book/$tutorId'
      path: '/book/$tutorId'
      fullPath: '/book/$tutorId'
      preLoaderRoute: typeof AuthenticatedBookTutorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/whiteboard': {
      id: '/_authenticated/admin/whiteboard'
      path: '/admin/whiteboard'
      fullPath: '/admin/whiteboard'
      preLoaderRoute: typeof AuthenticatedAdminWhiteboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tutors': {
      id: '/_authenticated/admin/tutors'
      path: '/admin/tutors'
      fullPath: '/admin/tutors'
      preLoaderRoute: typeof AuthenticatedAdminTutorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/classrooms': {
      id: '/_authenticated/admin/classrooms'
      path: '/admin/classrooms'
      fullPath: '/admin/classrooms'
      preLoaderRoute: typeof AuthenticatedAdminClassroomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentChildrenRoute: typeof AuthenticatedParentChildrenRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentChildrenRoute: AuthenticatedParentChildrenRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedAiTutorRoute: typeof AuthenticatedAiTutorRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedBecomeTutorRoute: typeof AuthenticatedBecomeTutorRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLabsRoute: typeof AuthenticatedLabsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClassroomsRoute: typeof AuthenticatedAdminClassroomsRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTutorsRoute: typeof AuthenticatedAdminTutorsRoute
  AuthenticatedAdminWhiteboardRoute: typeof AuthenticatedAdminWhiteboardRoute
  AuthenticatedBookTutorIdRoute: typeof AuthenticatedBookTutorIdRoute
  AuthenticatedClassroomRoomIdRoute: typeof AuthenticatedClassroomRoomIdRoute
  AuthenticatedTutorHolidaysRoute: typeof AuthenticatedTutorHolidaysRoute
  AuthenticatedWhiteboardReviewSessionIdRoute: typeof AuthenticatedWhiteboardReviewSessionIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedAiTutorRoute: AuthenticatedAiTutorRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedBecomeTutorRoute: AuthenticatedBecomeTutorRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLabsRoute: AuthenticatedLabsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminClassroomsRoute: AuthenticatedAdminClassroomsRoute,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTutorsRoute: AuthenticatedAdminTutorsRoute,
  AuthenticatedAdminWhiteboardRoute: AuthenticatedAdminWhiteboardRoute,
  AuthenticatedBookTutorIdRoute: AuthenticatedBookTutorIdRoute,
  AuthenticatedClassroomRoomIdRoute: AuthenticatedClassroomRoomIdRoute,
  AuthenticatedTutorHolidaysRoute: AuthenticatedTutorHolidaysRoute,
  AuthenticatedWhiteboardReviewSessionIdRoute:
    AuthenticatedWhiteboardReviewSessionIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TutorsRoute: TutorsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  TutorIdRoute: TutorIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
